services:
  notebook:
      build: notebook/
      ports:
        - "8888:8888"
      volumes:
        - ./:/home/jovyan/work/data
      environment:
        - GRANT_SUDO=yes
      networks:
        - Practice